name: CI - Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Clonar o repositório
      uses: actions/checkout@v3

    - name: ⚙️ Instalar .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: 📦 Restaurar dependências
      run: dotnet restore

    - name: 🧱 Build do projeto
      run: dotnet build --no-restore --configuration Release

    - name: ✅ Executar testes
      run: dotnet test --no-build --configuration Release --verbosity normal
